version: '3.8'
services:
  postgres:
    image: postgres:15
    env_file: infra/env/postgres.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build: ./api
    env_file: infra/env/api.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - ai-service

  ai-service:
    build: ./ai-service
    env_file: infra/env/ai.env
    ports:
      - "8001:8001"
    depends_on:
      - redis

volumes:
  pgdata:
